default_platform(:android)

platform :android do
  desc "Build aab file"
  lane :build do
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
  end

  desc "Release for alpha testing"
  lane :alpha_release_to_play_store do
    build
    upload_to_play_store(
      package_name: 'com.newsapi',
      track: "alpha",
      skip_upload_apk: true,
      aab: "app/build/outputs/bundle/release/app-release.aab"
    )
  end

  desc "Release for production"
  lane :production_release_to_play_store do
    build
    upload_to_play_store(
      package_name: 'com.newsapi',
      track: "production",
      skip_upload_apk: true,
      aab: "app/build/outputs/bundle/release/app-release.aab"
    )
  end
end
