# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

version_code = ENV["GITHUB_RUN_NUMBER"] || 86

platform :android do
  desc "Runs lint check"
  lane :lint do
    gradle(task: "lintDevRelease")
  end

  desc "Build Generate"

    # CMD fastlane Build gnerate
    desc "Build generate for QA"
    lane :build_android_dev do

      # Bundle the app
      gradle(
        task: 'bundle',
        build_type: 'Release',
        project_dir: "android/"
      )

      # Upload to Play Store's Internal Testing
      upload_to_play_store(
        package_name: 'com.newsapi',
        track: "internal",
      )

    end
end
