name: Build Pipeline Workflow

# Execute PR Pipeline Workflow on pull requests to master
on:
  release:
    type: [published]
    
jobs:
  release-android:
    name: Build staging app and release to alpha track android
    needs: [increment-app-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: Install packages
        run: |
          yarn install
          yarn react-native link
      - name: Install Fastlane
        run:  gem install fastlane
      - name: Bundle and Upload to PlayStore
        run: |
          cd android
          fastlane android alpha_release_to_play_store
        # run: bundle exec fastlane alpha_release_to_play_store
