name: Build Pipeline Workflow

# Execute PR Pipeline Workflow on pull requests to fastlane
on: 
  push:
    branches:
      - fastlane

jobs:
  build-production:
    runs-on: ubuntu-latest
  
    steps: 
    - name: Checkout Repository in Github VM
      uses: actions/checkout@v2
    - name: Run Node in Github VM
      uses: actions/setup-node@master
    - name: NPM Install Dependencies
      run: |
        npm install
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Gem Install Dependencies
      run: gem install bundler && bundle install
    - name: Install Fastlane
      run: |
        bundle install
        bundle update fastlane
    - name: Build Android App
      run: |
        cd android
        ./gradlew clean
        fastlane android android_release_build
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: newsApp.apk
        path: android/app/build/outputs/apk/release/    